Joyful Web

* What is this?

The Joyful website generator creates "static" websites authored in Org markup and rendered with [[http://jinja.pocoo.org/][Jinja2]] templates.  

* How does it work

Joyful Web provides a Python package with a command line interface.
You provide the content as Org and you direct its layout by providing
Jinja2 templates.  Ancillary static files (images, CSS, JS, etc) can
also be provided.  And, because it's Org, additional content may be
generated by source blocks during =org-mode= export.

** Joyful Generation 

Each =.org= file found is one "unit".  From it, various types of
things may be generated.  For example:

 - a web page
 - an entry in an RSS feed
 - a contribution to a tag cloud
 - whatever else one can dream up

The =joy= command line program can be used to process one Org file or
to aggregate information about many.  As the website gets larger it is
a good idea to automate the running of =joy= with a build tool such as [[https://waf.io/][Waf]].  

Each Org file can generate various derived files:

- =.body= :: an HTML fragment created by Emacs =org-mode= exporting the body of Org document
- =.json= :: a JSON representation of the =org-element= of the Org file
- =.revs= :: commit revision information about the Org file if it is maintained by Git
- etc :: ... dream up others ...

** CLI

The command line interface =joy= can be used to generate your website.
